tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "khanhas/tap"
tap "koekeishiya/formulae"
tap "zegervdv/zathura"
brew "pkg-config"
brew "python@3.9"
brew "autoconf"
brew "automake"
brew "bat"
brew "brew-cask-completion"
brew "ghc"
brew "cabal-install"
brew "cln", args: ["HEAD"]
brew "cmake"
brew "dbus"
brew "diff-so-fancy"
brew "djview4"
brew "exiftool"
brew "fdupes"
brew "libogg"
brew "libidn2"
brew "lame"
brew "libvorbis"
brew "libsndfile"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "gd"
brew "ginac"
brew "git"
brew "git-lfs"
brew "go"
brew "gradle"
brew "gtk-mac-integration"
brew "haskell-stack"
brew "highlight"
brew "htop"
brew "imagemagick"
brew "jdupes"
brew "jhead"
brew "oniguruma"
brew "jq"
brew "mas"
brew "micro"
brew "mupdf"
brew "node"
brew "openjdk"
brew "openssl@3"
brew "pandoc"
brew "pangomm"
brew "pdftk-java"
brew "perl"
brew "python@3.10"
brew "python@3.8"
brew "ruby"
brew "rustup-init"
brew "shpotify"
brew "switchaudio-osx"
brew "tldr"
brew "tmux"
brew "trash"
brew "unar"
brew "vim"
brew "wget"
brew "youtube-dl"
brew "z"
brew "zsh-completions"
brew "khanhas/tap/spicetify-cli"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
brew "zegervdv/zathura/girara", args: ["HEAD"]
brew "zegervdv/zathura/zathura", args: ["HEAD", "with-synctex"]
brew "zegervdv/zathura/zathura-cb"
brew "zegervdv/zathura/zathura-djvu"
brew "zegervdv/zathura/zathura-pdf-poppler"
cask "adobe-acrobat-reader"
cask "adobe-digital-editions"
cask "alacritty"
cask "aldente"
cask "anki"
cask "audacity"
cask "battle-net"
cask "calibre"
cask "db-browser-for-sqlite"
cask "discord"
cask "dosbox"
cask "eqmac"
cask "firefox"
cask "gimp"
cask "google-chrome"
cask "hiddenbar"
cask "inkscape"
cask "keepassxc"
cask "kobo"
cask "mactex"
cask "megasync"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "microsoft-teams"
cask "minecraft"
cask "monitorcontrol"
cask "mouse-fix"
cask "musescore"
cask "numi"
cask "obs"
cask "openemu"
cask "openttd"
cask "prismlauncher"
cask "rectangle"
cask "sage"
cask "sioyek"
cask "skim"
cask "slack"
cask "spotify"
cask "steam"
cask "syntax-highlight"
cask "thunderbird"
cask "transmission"
cask "vlc"
cask "vscodium"
cask "zoom"
mas "Be Focused", id: 973134470
mas "ColorSlurp", id: 1287239339
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
