tap "cherche/custom", "git@github.com:cherche/homebrew-custom.git"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "khanhas/tap"
tap "koekeishiya/formulae"
tap "zegervdv/zathura"
brew "python@3.9"
brew "pkg-config"
brew "bat"
brew "brew-cask-completion"
brew "ghc"
brew "cabal-install"
brew "cmake"
brew "dbus", restart_service: true
brew "libogg"
brew "libidn2"
brew "lame"
brew "libvorbis"
brew "libsndfile"
brew "ffmpeg"
brew "gd"
brew "git"
brew "git-lfs"
brew "go"
brew "python@3.8"
brew "graphviz"
brew "gtk-mac-integration"
brew "haskell-stack"
brew "highlight"
brew "htop"
brew "imagemagick"
brew "jack"
brew "m-cli"
brew "mas"
brew "mercurial"
brew "micro"
brew "node"
brew "onefetch"
brew "oniguruma"
brew "p7zip"
brew "pangomm"
brew "pdftk-java"
brew "perl"
brew "portaudio"
brew "progress"
brew "ruby"
brew "rustup-init"
brew "shpotify"
brew "tmux"
brew "trash"
brew "unar"
brew "youtube-dl"
brew "z"
brew "heroku/brew/heroku"
brew "khanhas/tap/spicetify-cli"
brew "koekeishiya/formulae/skhd"
brew "zegervdv/zathura/girara", args: ["HEAD"]
brew "zegervdv/zathura/zathura", args: ["HEAD"]
brew "zegervdv/zathura/zathura-cb"
brew "zegervdv/zathura/zathura-djvu"
brew "zegervdv/zathura/zathura-pdf-mupdf"
brew "zegervdv/zathura/zathura-pdf-poppler"
cask "adobe-acrobat-reader"
cask "adobe-digital-editions"
cask "alacritty"
cask "amethyst"
cask "anki"
cask "atom"
cask "audacity"
cask "battle-net"
cask "blackhole-16ch"
cask "calibre"
cask "citra"
cask "colorpicker"
cask "discord"
cask "djview"
cask "dosbox"
cask "firefox"
cask "foxitreader"
cask "gimp"
cask "google-backup-and-sync"
cask "google-chrome"
cask "hyper"
cask "inkscape"
cask "keepassxc"
cask "kobo"
cask "league-of-legends"
cask "mactex"
cask "megasync"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-office"
cask "microsoft-teams"
cask "minecraft"
cask "musescore"
cask "ngrok"
cask "numi"
cask "obs"
cask "openemu"
cask "openttd"
cask "qutebrowser"
cask "rectangle"
cask "sage@9.2"
cask "scribus"
cask "spotify"
cask "steam"
cask "thunderbird"
cask "transmission"
cask "vlc"
cask "xournalpp-nightly"
cask "xquartz"
cask "zoom"
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Rakuten Canada Button", id: 1485926199
mas "Userscripts", id: 1463298887
mas "Vimari", id: 1480933944
